name: shamanicperformance
favicon: null
layout_spectrum: 0.618243
typography_spectrum: 0.517736
title: shamanic trance theatre
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#97896F'
    - '#D1DAE3'
    - '#5E5F61'
  brandStrength: 0.84375
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.81081
purpose:
  - name: null
    item: null
    url: null
